### ISSUE TITLE
About page not showing correct data

### ISSUE THREAD

**Issue by perry-mitchell** [LouisBarranqueiro/tranquilpeak-hexo-theme#117]
Hi again

I apologise if I'm doing something stupid, but I cannot seem to get the data coming through on my about page using `hexo server`:

<img width="504" alt="screen shot 2015-10-11 at 12 22 36 am" src="https://cloud.githubusercontent.com/assets/3869469/10413344/55c565ca-6fae-11e5-96d9-49eff444f717.png">

From the config:
```
author:
    email: perry@perrymitchell.net
    bio: "I'm a web and applications developer from Brisbane, Australia."
    job: Software engineer
    location: Helsinki
    # Your profile picture located in folder `source/_images/` (development)
    # or in `source/assets/images/` (production).
    # Overwritten by your gravatar image if `gravatar_image` is enabled
    picture:
    twitter: perry_mitchell
    google_plus: 108400613863965057197
```

In the code from the 1.3.0 download, bio at least wasn't there, but I pasted it back from by 1.2.0 version. Any reason why I'd be seeing this? It's the same when I clean/generate/deploy it.

**Comment by LouisBarranqueiro** [comment]
Yeah, because your bio and your job has to be filled in each languages files. It's written in comment. 
``` yml
# Author
# Your biography and your job is editable in each languages files in `languages` folder
author:
    email:
    location:
    # Your profile picture located in folder `source/_images/` (development)
    # or in `source/assets/images/` (production)
    # or you can use an external url
    # Overwritten by your gravatar image if `gravatar_email` is filled
    picture:
    # Your Twitter username without the @. E.g : `tranquilpeak`
    twitter:
    # Your google plus profile id. E.g : `+Tranquilpeak` or `123812884128439`
    google_plus:
```
