### ISSUE TITLE
Two header picture

### ISSUE THREAD

**Issue by xiejiachen** [LouisBarranqueiro/tranquilpeak-hexo-theme#169]
By using uploaded codes.

My web shows 2 header picture.

Really confused.

xiejiachen.github.io

**Comment by LouisBarranqueiro** [comment]
in your `_config.yml` file :  

``` yml
header:
    right_link:
        url: /#about
        icon:
        class:
```
`url` variable cannot be empty.
