### ISSUE TITLE
author.bio and author.job do not work

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#85]
I have edit the setting in _config.yml file of the theme, but it does not work well.

![enter image description here](https://lh3.googleusercontent.com/-4qr10MbM30o/VdmewvpauJI/AAAAAAAABLE/KGinpoQmxOo/s800/BaiduShurufa_2015-8-23_18-15-41.png)

![enter image description here](https://lh3.googleusercontent.com/-b3ZDdw2dR44/VdmfNO40BlI/AAAAAAAABLY/CtIfC47v1RI/s800/BaiduShurufa_2015-8-23_18-15-56.png)

**Comment by kaedea** [comment]
using release 1.3.0

**Comment by LouisBarranqueiro** [comment]
That not the config file of 1.3.0 version. 
Vonfiguration file (v1.3.0) :  
``` yml
# Author
# Your biography and your job is editable in each languages files in `languages` folder
author:
    email:
    location:
    # Your profile picture located in folder `source/_images/` (development)
    # or in `source/assets/images/` (production).
    # Overwritten by your gravatar image if `gravatar_image` is enabled
    picture:
    # Your Twitter username without the @. E.g : `tranquilpeak`
    twitter:
    # Your google plus profile id. E.g : `+Tranquilpeak` or `123812884128439`
    google_plus:
```

Your biography and your job is editable in each languages files in `languages` folder
