### ISSUE TITLE
Open external link in new tab from Sidebar

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#87]
Now open external links from sidebar will not open in new tab. The setting of HEXO's config.yml works only in post concent. Please consider to add this feature.
Me myself use JS to support this in the following code, but I think this is not so good.

```javascript
$(document).ready(function() {
   $('a').each(function() {
      var a = new RegExp('/' + window.location.host + '/');
      if (!a.test(this.href)) {
      $(this).attr("target","_blank");
      }
   });
});
···

**Comment by h404bi** [comment]
I consider not everyone would need this feature. :smiley:

**Comment by LouisBarranqueiro** [comment]
I agree with @h404bi. I think that open external link in new tab is the right default behavior.

**Comment by kaedea** [comment]
I am not asking to add my script.
I need this feature to open an external link in a new tab. And this script works for me (relative link will not open in new tab). But i think using JS is not better rather than using CSS.
I ask for help `how to use css to support this feature`.

**Comment by h404bi** [comment]
Ok, I misunderstood `Please consider to add this feature.`...
I guess you want to let those  external links such as `GitHub`, `Twitter` to be opened in a new tab, right? If yes, actually the theme has the implementation, see [/layout/partial/sidebar.ejs#L19](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/layout%2F_partial%2Fsidebar.ejs#L19).

**Comment by LouisBarranqueiro** [comment]
As @h404bi said, the theme has already this behavior for external links in sidebar. Don't really understand what do you want :D

**Comment by kaedea** [comment]
I am using release 1.3.0, setting the following code for external link of my github page. It will not working, opening github in the current tab.

```YAML
 author_links:
         github:
             title: global.github
             url: https://github.com/kaedea
             icon: github
        # stack_overflow:
        #     title: global.stack_overflow
        #     url: http://stackoverflow.com/users
        #     icon: stack-overflow
        # twitter:
        #     title: global.twitter
        #     url: https://twitter.com/
        #     icon: twitter
        # facebook:
        #     title: global.facebook
        #     url: https://facebook.com/
        #     icon: facebook
        # google_plus:
        #     title: global.google_plus
        #     url: https://plus.google.com/
        #     icon: google-plus
        # linked_in:
        #     title: global.linked_in
        #     url: https://www.linkedin.com/profile/
        #     icon: linkedin
         mail:
             title: global.mail
             url: mailto:kidhaibara@gmail.com
             icon: envelope-o
```
