### ISSUE TITLE
Archives page displays wrong layout if url set to /archives

### ISSUE THREAD

**Issue by h404bi** [LouisBarranqueiro/tranquilpeak-hexo-theme#90]
Normally enable archives page:
a. `hexo new page "all-archives"`
b. source/all-archives/index.md:
```
title: "all-archives"
layout: "all-archives"
---
```
c. theme `_config.yml`:
```yaml
...
archives:
            title: global.archives
            url: /all-archives
            icon: archive
...
```

But if:
a. `hexo new page "archives"`
b. source/archives/index.md:
```md
title: "archives"
layout: "all-archives"
---
```
c. theme `_config.yml`:
```yaml
...
archives:
            title: global.archives
            url: /archives
            icon: archive
...
```

Archives page will not use the `all-archives` layout, and display like index page. However, tags page and categories page works with similar settings. Strange.
